### ISSUE TITLE
BOS中，是否有可视化的图形工具，可以方便管理

### ISSUE THREAD

**Issue by leeight** [baidubce/bce-sdk-js#14]
搬运工：http://developer.baidu.com/forum/topic/show?topicId=5219

考虑基于 electron 和 bce-sdk-js 弄一个跨平台的本地版本的？

**Comment by leeight** [comment]
阿里云的OSS有一个比较好用的

**Comment by otakustay** [comment]
https://github.com/otakustay/bos-desktop

简单确认了一个仿ajax的基本流程，后续我打算用react来做前端，欢迎有兴趣的一起搞

**Comment by leeight** [comment]
半官方性质的客户端：https://github.com/mudio/bce-client
