### ISSUE TITLE
BOSClient不能上传跨页面传递过来的File

### ISSUE THREAD

**Issue by mikab** [baidubce/bce-sdk-js#39]
假设有两个页面A和B，程序设置了用户在A页面里通过Dropzone（http://www.dropzonejs.com/）等控件选择了某些文件，然后通过js对象的方式直接传递给B页面，B页面里使用BOSClient去上传A页面里传递过来的File对象时会失败。

通过调试，我们在http_client.js里把isXHR2Compatible函数的返回值强行设置为 true时，可以让BOSClient上传文件。猜测是其他页面传递过来的File不满足obj instanceof Blob的判断。

使用场景：我们的用户需要一次性在页面上上传成百上千个文件，并且系统的页面布局还是传统的FRAMESET布局，用户需要经常操作的内容是通过中间区域的Frame不断的切换页面URL来达成的。因为一次性上传的文件比较多，不能让用户一直等待文件全部上传完成后才能执行后继的操作。因此我们使用的方法是将BOSClient上传的功能放在frameset里不常变化的页面里，用户提交文件上传的操作只是把文件对象传递给上传页面而已，从而实现所谓的“后台上传”的功能。

**Comment by leeight** [comment]
`bce-sdk-js` 主要是在服务端运行的，如果要在浏览器端上传文件，考虑使用 <https://leeight.github.io/bce-bos-uploader/>
