### ISSUE TITLE
putObjectFromFile如何重命名文件

### ISSUE THREAD

**Issue by hinet** [baidubce/bce-sdk-js#52]
当上传同名文件时如果没有重命名的话会覆盖之前的文件，假如是两个不同的文件但是名称一样，不能重命名是不行的

**Comment by mudio** [comment]
1. 相同`ObjectKey`只能对应一个文件，就想你计算机本地项目补录下不会存在名字相同的两个文件
2. 针对你的需求，你可以先判断目标文件是否存在，如果存在这指定不同的ObjectKey
