### ISSUE TITLE
上传报错，Invalid non-string/buffer chunk

### ISSUE THREAD

**Issue by zhaoPengInGithub** [baidubce/bce-sdk-js#58]
如题，转成arrayBuffer 也报错
`TypeError: Invalid non-string/buffer chunk
    at validChunk (_stream_writable.js?a6d8:304)
    at module.exports.Writable.write (_stream_writable.js?a6d8:332)
    at HttpClient._sendRequest (http_client.js?67c7:358)
    at HttpClient._doRequest (http_client.js?67c7:195)
    at eval (http_client.js?67c7:131)
    at _fulfilled (q.js?bb27:854)
    at eval (q.js?bb27:883)
    at Promise.promise.promiseDispatch (q.js?bb27:816)
    at eval (q.js?bb27:570)
    at runSingle (q.js?bb27:137)`
 js 代码如下（使用arrayBuffer）;
`var ext = file.name.split(/\./g).pop();
      var mimeType = MimeType.guess(ext);
      var options = {
        'Content-Type': mimeType
      };

      var reader = new FileReader();
      reader.readAsArrayBuffer(file);
      reader.onload = function(e){
        bosClient.putObjectFromBlob(bucket,file.name,e.target.result,options).then(res=>{
        console.log(res);
      }).catch(err=>{
        console.log(err);
      })
      }`

第二种写法：
`bosClient.putObjectFromBlob(bucket,file.name,file,options).then(res=>{
        console.log(res);
      }).catch(err=>{
        console.log(err);})`
全部报错，好像是用是stream来传的

**Comment by lvgithub** [comment]
遇到同样问题，解决了吗

**Comment by mudio** [comment]
```javascript
const client = new baidubce.sdk.BosClient({
    credentials: {
        ak: 'your ak',
        sk: 'your sk'
    },
    endpoint: 'http://bj.bcebos.com'
});

const blob = new Blob(['demo data']);

const reader = new FileReader();
reader.readAsArrayBuffer(blob); // or file stream

reader.onload = () => {
    client.putObjectFromBlob('your_bucket', `demo/blob`, new Blob([reader.result])).then(
        res => console.log(`Blob object has uploaded! tag => ${res.http_headers.etag}`)
    );
};
```

**Comment by hiwangman** [comment]
@zhaoPengInGithub 请问你这个问题解决了吗？

**Comment by redredredredredred** [comment]
import { BosClient } from '@baiducloud/sdk/dist/baidubce-sdk.bundle' 可以解决这个问题
