### ISSUE TITLE
调用AI下面的接口有比较详细的文档或示例吗？

### ISSUE THREAD

**Issue by xiaoshuaishuai319** [baidubce/bce-sdk-js#60]
调用AI下面的接口有比较详细的文档或示例吗？
看到是有相关FACR OCR单独的JS 
没找到具体的示例或文档

**Comment by mudio** [comment]
- 暂时未提供相关client, 可以继承bce-base-client扩展功能
- AI相关API文档请参考官网 https://cloud.baidu.com/
