### ISSUE TITLE
angular 中本地开发没问题，服务器上使用sdk报签名错？

### ISSUE THREAD

**Issue by wushuxuan** [baidubce/bce-sdk-js#66]
在angular中使用本地开发时正常的，但是打包后在nginx中配置跨域，服务器上使用sdk请求数据一直报SignatureDoesNotMatch错误，是那里出错了么？

![image](https://user-images.githubusercontent.com/30644407/63737744-01222d00-c8ba-11e9-9376-aaf0cf0118c7.png)

**Comment by mudio** [comment]
新版修复了此问题~
