### ISSUE TITLE
rc14 升级到 rc16以后 STS成员没了

### ISSUE THREAD

**Issue by yunfan** [baidubce/bce-sdk-js#69]
之前在用 rc14这个版本 是在ts里用
最近想升级到rc16 结果发现STS这个成员没了 请问什么时候可以修正下？

**Comment by mudio** [comment]
我看下



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: yunfan <notifications@github.com&gt;
发送时间: 2020年6月9日 14:09
收件人: baidubce/bce-sdk-js <bce-sdk-js@noreply.github.com&gt;
抄送: Subscribed <subscribed@noreply.github.com&gt;
主题: 回复：[baidubce/bce-sdk-js] rc14 升级到 rc16以后 STS成员没了 (#69)





 
之前在用 rc14这个版本 是在ts里用
 最近想升级到rc16 结果发现STS这个成员没了 请问什么时候可以修正下？

**Comment by mudio** [comment]
`STS`还在，回滚声明文件了
